services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.12.0 # 
    container_name: mealie
    restart: always
    ports:
        - "9925:9000" # 
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - mealie-data:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: false
      PUID: 1000
      PGID: 1000
      TZ: America/Anchorage
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: https://mealie.crispterrile.com
      # Database Settings
      DB_ENGINE: postgres
      POSTGRES_USER: mealie
      POSTGRES_PASSWORD: ${MEALIE_DB_PASSWORD}
      POSTGRES_SERVER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: mealie
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    volumes:
      - mealie-pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${MEALIE_DB_PASSWORD}
      POSTGRES_USER: mealie
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3

  link:
    image: fractalnetworks/gateway-client:latest
    environment:
      LINK_DOMAIN: mealie.crispterrile.com
      EXPOSE: mealie:9000
      GATEWAY_CLIENT_WG_PRIVKEY: ${CLIENT_WG_PRIVKEY}
      GATEWAY_LINK_WG_PUBKEY: ${GATEWAY_WG_PUBKEY}
      GATEWAY_ENDPOINT: ${GATEWAY_IP}
      # Remove following to disable basic authentication
      #BASIC_AUTH: admin:admin
      # Remove following line to get certs from Let's Encrypt
      # TLS_INTERNAL: true
      # CADDY_TLS_PROXY: true
      # CADDY_TLS_INSECURE: true
      # FORWARD_ONLY: true
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
# #     uncomment to preserve tls certs
#     volumes:
#       - caddy_data:/data
# # uncomment to preserve tls certs
# volumes:
#   caddy_data:



volumes:
  mealie-data:
  mealie-pgdata: