services:
  newt:
    image: fosrl/newt:1.11.0
    container_name: newt-edge-client
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - pangolin
    restart: unless-stopped
    environment:
      - PANGOLIN_ENDPOINT=${PANGOLIN_ENDPOINT}
      - NEWT_ID=${NEWT_ID}
      - NEWT_SECRET=${NEWT_SECRET}
      - DOCKER_SOCKET=/var/run/docker.sock

networks:
  pangolin:
    external: true