services:
  newt:
    image: fosrl/newt:1.11.0
    container_name: newt-edge-client
    networks:
      - pangolin_site
    restart: unless-stopped
    environment:
      - PANGOLIN_ENDPOINT=${PANGOLIN_ENDPOINT}
      - NEWT_ID=${NEWT_ID}
      - NEWT_SECRET=${NEWT_SECRET}


networks:
  pangolin_site:
    external: true