version: '3'

services:

  plex:
    image: plexinc/pms-docker
    container_name: plex
    restart: always
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    environment:
      - TZ=America/Los_Angeles
      - HOSTNAME=${MEDIA_SERVER_NAME}
      - ADVERTISE_IP="http://${MEDIA_SERVER_IP}:32400"
      - ALLOWED_NETWORKS="192.168.1.0/24"
    volumes:
      - ${PLEX_CONFIG_DIR}:/config
      - ${PLEX_MEDIA_DIR}:/media/NAS
      - new_plex_library:/media/truenas
      

  tautulli:
    container_name: tautulli
    image: linuxserver/tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - tautulli_config:/config
    ports:
      - 8181:8181
    restart: unless-stopped

volumes:

  tautulli_config:
    name: tautulli_config
    external: true

  plex_library:
    name: plex_library
    external: true
  new_plex_library:
    name: new_plex_library
    external: true
