version: "3"
services:
  rtlamr:
    container_name: rtlamr2mqtt
    image: allangood/rtlamr2mqtt
    restart: unless-stopped
    devices:
      - /dev/bus/usb
    environment:
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - METER_ID=${METER_ID}
    volumes:
      - ${PWD}/config/rtlamr2mqtt.yaml:/etc/rtlamr2mqtt.yaml
      - /opt/rtlamr2mqtt/data:/var/lib/rtlamr2mqtt