version: '3'

services:
  traefik:
    image: traefik:v2.2
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik-proxy
    environment:
      - DO_AUTH_TOKEN=${DO_AUTH_TOKEN}
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik-data/:/etc/traefik/:ro

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefikproxy.${DOMAIN}`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_USER}:${TRAEFIK_PW}"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefikproxy.${DOMAIN}`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=dns"
      - "traefik.http.routers.traefik-secure.service=api@internal"

  portainer:
    image: portainer/portainer-ee:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik-proxy
    ports:
      - 8000:8000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    labels:
      - "traefik.enable=true"
    #  - "traefik.http.routers.portainer.entrypoints=http"
    #  - "traefik.http.routers.portainer.rule=Host(`services.${DOMAIN}`)"
      - "traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.portainer.middlewares=portainer-https-redirect"
      - "traefik.http.routers.portainer-secure.entrypoints=https"
      - "traefik.http.routers.portainer-secure.rule=Host(`services.${DOMAIN}`)"
      - "traefik.http.routers.portainer-secure.tls=true"
      - "traefik.http.routers.portainer-secure.tls.certresolver=dns"
      - "traefik.http.routers.portainer-secure.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.docker.network=traefik-proxy"

  consul-server:
    image: hashicorp/consul:1.11.2
    container_name: consul-server
    restart: always
    volumes:
     - ./consul-server/server.json:/consul/config/server.json:ro
     - ./certs/:/consul/config/certs/:ro
    networks:
      - traefik-proxy
  #  ports:
  #    - "8500:8500"
  #    - "8600:8600/tcp"
  #    - "8600:8600/udp"  
    labels:
      - "traefik.enable=true"
    #  - "traefik.http.routers.portainer.entrypoints=http"
    #  - "traefik.http.routers.portainer.rule=Host(`consul.${DOMAIN}`)"
      - "traefik.http.middlewares.consul-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.consul.middlewares=consul-https-redirect"
      - "traefik.http.routers.consul-secure.entrypoints=https"
      - "traefik.http.middlewares.consul-auth.basicauth.users=${TRAEFIK_USER}:${TRAEFIK_PW}"
      - "traefik.http.routers.consul-secure.rule=Host(`consul.${DOMAIN}`)"
      - "traefik.http.routers.consul-secure.tls=true"
      - "traefik.http.routers.consul-secure.tls.certresolver=dns"
      - "traefik.http.routers.consul-secure.service=consul"
      - "traefik.http.services.consul.loadbalancer.server.port=8500"
      - "traefik.docker.network=traefik-proxy"

  wireguard-tunnel-server:
    image: ghcr.io/digitallyrefined/docker-wireguard-tunnel:v3
    container_name: wireguard-tunnel-server
    environment:
      # Update to your domain
      - DOMAIN=wireguard-tunnel.example.com
      # Number of peers to auto generate config for
      - PEERS=artemis
      # Services to expose format (comma-separated)
      # SERVICES=peer-id:peer-container-name:peer-container-port:expose-port-as
      - SERVICES=peer1:radarr:7878:7878,peer1:sonarr:8989:8989
    cap_add:
      - NET_ADMIN
    volumes:
      - wireguard:/etc/wireguard
    restart: unless-stopped
    ports:
      - '51820:51820/udp'
    networks:
      - "traefik-proxy"
    labels:
      traefik.enable: true
      traefik.http.routers.radarr.entrypoints: web,websecure
      traefik.http.routers.radarr.rule: Host(`radarr.${DOMAIN}`) # Update to your domain
      traefik.http.routers.radarr.tls: true
      traefik.http.routers.radarr.tls.certresolver: dns
      traefik.http.services.radarr.loadbalancer.server.port: 7878

      traefik.http.routers.sonarr.entrypoints: web,websecure
      traefik.http.routers.sonarr.rule: Host(`sonarr.${DOMAIN}`) # Update to your domain
      traefik.http.routers.sonarr.tls: true
      traefik.http.routers.sonarr.tls.certresolver: dns
      traefik.http.services.sonarr.loadbalancer.server.port: 8989

networks:
  traefik-proxy:
    external: true

volumes:
  portainer_data:
  wireguard: